{{- if .Values.faults.testFail }}
apiVersion: v1
kind: Pod
metadata:
  name: fault-app
  annotations:
    "helm.sh/hook": test-success
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  containers:
    - name: fault
      image: alpine:3.11
      command: ['/bin/sh']
      args:  ['-c', 'exit 1']
  restartPolicy: Never
{{- end }}